### ISSUE TITLE
i don't understand what is going on

### ISSUE THREAD

**Issue by folakemiariyo** [londonappbrewery/Flutter-Course-Resources#39]
i am having issues in my pubspec.yaml file

**Comment by folakemiariyo** [comment]
name: personal_expense
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/waiting.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
    - family:  QuickSand 
      fonts:
        - asset: assets/fonts/QuickSand-Regular.ttf
        - asset: assets/fonts/QuickSand-Bold.ttf
          weight: 700
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

**Comment by WojuadeAA** [comment]
have been able to solve the issue?

**Comment by WojuadeAA** [comment]
if you haven't what is the error message on the pubspec.yaml file?

**Comment by mandata5010** [comment]
Hi, I probably have a problem with the pubspec.yaml file too? Could you help, I am a new user and I'm trying to learn everything? Included attachments (2)?
![code problem](https://user-images.githubusercontent.com/76627939/103443100-6df2c780-4c64-11eb-8f54-e7a6e525b35c.JPG)
![code](https://user-images.githubusercontent.com/76627939/103443105-7814c600-4c64-11eb-8e51-ccd2f2acd2c1.JPG)
Please, help me !

**Comment by shazlycode** [comment]
Hi Could you please send pubspec.yaml screen shot to be able to help you.ThanksOn 1 Jan 2021 8:08 pm, mandata5010 <notifications@github.com> wrote:
Hi, I probably have a problem with the pubspec.yaml file too? Could you help, I am a new user and I'm trying to learn everything? Included attachments (2)?


Please, help me !

**Comment by mandata5010** [comment]
Hi, did you mean this? Also included is a pub?
Thank you.
![pubspec](https://user-images.githubusercontent.com/76627939/103483224-75de7300-4dee-11eb-9899-227ed531bc28.JPG)
![pubget](https://user-images.githubusercontent.com/76627939/103483232-7a0a9080-4dee-11eb-8874-50760294c6e3.JPG)

**Comment by prateek-aher** [comment]
The code shown in your `pubspec.yaml` file Shouldn't be there in the first place. My guess is, you copied the code and pasted it in the `pubspec.yaml` file when you should have pasted it in `main.dart`. The original code in the YAML file got overwritten. 

It is throwing an error because the YAML file has got unrecognized code in it.

This what `pubspec.yaml` file looks originally. You can copy-paste it there.
```yaml
name: Quotes
description: Read a list of quotes frome famous authors.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```
